function [ b ] = bad_trial( nsubj,sess,g,kk,trial )
%BAD_TRIAL funzione che ritorna TRUE se si tratta di un badtrial
%    INPUT: nsubj,sess,g,kk,trial, info utili per identificare i badtrial
%    OUTPUT:b, booleano in output

switch nsubj
    case 1 
        if ((sess==1 & g==2 & kk==1 & trial==1) ...
                |(sess==3 & g==1 & kk==1 & trial==1) ...
                |(sess==4 & g==2 & kk==1 & (trial==1|trial==2)) ...
                | (sess==7 & g==1 & kk==1 & trial==4)...
                | (sess==7 & g==3 & kk==1 & trial==2) ...
            )
            b=1;
        else
            b=0;
        end
    case 2 
        if ((sess==4 & g==1 & kk==1 & trial==7)...
                |(sess==4 & g==3 & kk==1 & trial==3)...
                )
            b=1;
        else
            b=0;
        end
    case 3 
        if ((sess==1 & g==1 & kk==2 & trial==3) ...
                |(sess==2 & g==1 & kk==1 & (trial==2 | trial==17)) ...
                |(sess==3 & g==2 & kk==1 & trial==12) ...
                 |(sess==1 & g==3 & kk==1 & (trial==3 | trial==20)) ...
                |(sess==4 & g==1 & kk==1 & trial==20) ...
                |(sess==6 & g==3 & kk==1 & trial==9) ...
                | (sess==5 & g==2 & kk==1 & (trial==3 | trial==5)) )
            b=1;
        else
            b=0;
        end
    case 4 
        if ((sess==3 & (g==1 | g==2) & kk==1 & trial==1) ...
                |(sess==7 & g==1 & kk==1 & trial==1) ...
                |(sess==8 & g==1 & kk==1 & trial==2) ...
                | (sess==8 & g==2 & kk==1 & trial==1) )
            b=1;
        else
            b=0;
        end
end

end

