%varianza reach orizzontale
figure
subplot(2,3,1)
bar([varianzaxHipl_hor(:,1) [varianzaxHipl_hor(1,7); varianzaxHipl_hor(2,10); varianzaxHipl_hor(3,6)]])
title('Hip left variance_x Hor')
subplot(2,3,2)
bar([varianzayHipl_hor(:,1) [varianzayHipl_hor(1,7); varianzayHipl_hor(2,10); varianzayHipl_hor(3,6)]])
title('Hip left variance_y Hor')
subplot(2,3,3)
bar([varianzazHipl_hor(:,1) [varianzazHipl_hor(1,7); varianzazHipl_hor(2,10); varianzazHipl_hor(3,6)]])
title('Hip left variance_z Hor')
subplot(2,3,4)
bar([varianzaxHipr_hor(:,1) [varianzaxHipr_hor(1,7); varianzaxHipr_hor(2,10); varianzaxHipr_hor(3,6)]])
title('Hip right variance_x Hor')
subplot(2,3,5)
bar([varianzayHipr_hor(:,1) [varianzayHipr_hor(1,7); varianzayHipr_hor(2,10); varianzayHipr_hor(3,6)]])
title('Hip right variance_y Hor')
subplot(2,3,6)
bar([varianzazHipr_hor(:,1) [varianzazHipr_hor(1,7); varianzazHipr_hor(2,10); varianzazHipr_hor(3,6)]])
title('Hip right variance_z Hor')
% varianza reach verticale
figure
subplot(2,3,1)
bar([varianzaxHipl_vert(:,1) [varianzaxHipl_vert(1,7); varianzaxHipl_vert(2,10); varianzaxHipl_vert(3,6)]])
title('Hip left variance_x vert')
subplot(2,3,2)
bar([varianzayHipl_vert(:,1) [varianzayHipl_vert(1,7); varianzayHipl_vert(2,10); varianzayHipl_vert(3,6)]])
title('Hip left variance_y vert')
subplot(2,3,3)
bar([varianzazHipl_vert(:,1) [varianzazHipl_vert(1,7); varianzazHipl_vert(2,10); varianzazHipl_vert(3,6)]])
title('Hip left variance_z vert')
subplot(2,3,4)
bar([varianzaxHipr_vert(:,1) [varianzaxHipr_vert(1,7); varianzaxHipr_vert(2,10); varianzaxHipr_vert(3,6)]])
title('Hip right variance_x vert')
subplot(2,3,5)
bar([varianzayHipr_vert(:,1) [varianzayHipr_vert(1,7); varianzayHipr_vert(2,10); varianzayHipr_vert(3,6)]])
title('Hip right variance_y vert')
subplot(2,3,6)
bar([varianzazHipr_vert(:,1) [varianzazHipr_vert(1,7); varianzazHipr_vert(2,10); varianzazHipr_vert(3,6)]])
title('Hip right variance_z vert')
% rapporto tra varianze
figure
subplot(2,2,1)
bar([varianzazHipl_hor(:,1)./(varianzaxHipl_hor(:,1)+varianzayHipl_hor(:,1)) [varianzazHipl_hor(1,7)./(varianzaxHipl_hor(1,7)+varianzayHipl_hor(1,7)); varianzazHipl_hor(2,10)./(varianzaxHipl_hor(2,10)+varianzayHipl_hor(2,10)); varianzazHipl_hor(3,6)./(varianzaxHipl_hor(3,6)+varianzayHipl_hor(3,6))]])
title('HipL variance ratio ReachH')
subplot(2,2,2)
bar([varianzazHipr_hor(:,1)./(varianzaxHipr_hor(:,1)+varianzayHipr_hor(:,1)) [varianzazHipr_hor(1,7)./(varianzaxHipr_hor(1,7)+varianzayHipr_hor(1,7)); varianzazHipr_hor(2,10)./(varianzaxHipr_hor(2,10)+varianzayHipr_hor(2,10)); varianzazHipr_hor(3,6)./(varianzaxHipr_hor(3,6)+varianzayHipr_hor(3,6))]])
title('HipR variance ratio ReachH')
subplot(2,2,3)
bar([varianzaxHipl_vert(:,1)./(varianzayHipl_vert(:,1)+varianzazHipl_vert(:,1)) [varianzaxHipl_vert(1,7)./(varianzayHipl_vert(1,7)+varianzazHipl_vert(1,7)); varianzaxHipl_vert(2,10)./(varianzayHipl_vert(2,10)+varianzazHipl_vert(2,10)); varianzaxHipl_vert(3,6)./(varianzayHipl_vert(3,6)+varianzazHipl_vert(3,6))]])
title('HipL variance ratio ReachV')
subplot(2,2,4)
bar([varianzaxHipr_vert(:,1)./(varianzayHipr_vert(:,1)+varianzazHipr_vert(:,1)) [varianzaxHipr_vert(1,7)./(varianzayHipr_vert(1,7)+varianzazHipr_vert(1,7)); varianzaxHipr_vert(2,10)./(varianzayHipr_vert(2,10)+varianzazHipr_vert(2,10)); varianzaxHipr_vert(3,6)./(varianzayHipr_vert(3,6)+varianzazHipr_vert(3,6))]])
title('HipR variance ratio ReachV')

figure
subplot(2,2,1)
bar([varianzazHipl_hor(:,1)./(varianzaxHipl_hor(:,1)+varianzayHipl_hor(:,1)+varianzazHipl_hor(:,1)) [varianzazHipl_hor(1,7)./(varianzaxHipl_hor(1,7)+varianzayHipl_hor(1,7)+varianzazHipl_hor(1,7)); varianzazHipl_hor(2,10)./(varianzaxHipl_hor(2,10)+varianzayHipl_hor(2,10)+varianzazHipl_hor(2,10)); varianzazHipl_hor(3,6)./(varianzaxHipl_hor(3,6)+varianzayHipl_hor(3,6)+varianzazHipl_hor(3,6))]])
title('HipL variance ratio ReachH')
subplot(2,2,2)
bar([varianzazHipr_hor(:,1)./(varianzaxHipr_hor(:,1)+varianzayHipr_hor(:,1)+varianzazHipr_hor(:,1)) [varianzazHipr_hor(1,7)./(varianzaxHipr_hor(1,7)+varianzayHipr_hor(1,7)+varianzazHipr_hor(1,7)); varianzazHipr_hor(2,10)./(varianzaxHipr_hor(2,10)+varianzayHipr_hor(2,10)+varianzazHipr_hor(2,10)); varianzazHipr_hor(3,6)./(varianzaxHipr_hor(3,6)+varianzayHipr_hor(3,6)+varianzazHipr_hor(3,6))]])
title('HipR variance ratio ReachH')
subplot(2,2,3)
bar([varianzaxHipl_vert(:,1)./(varianzayHipl_vert(:,1)+varianzazHipl_vert(:,1)+varianzaxHipl_vert(:,1)) [varianzaxHipl_vert(1,7)./(varianzayHipl_vert(1,7)+varianzazHipl_vert(1,7)+varianzaxHipl_vert(1,7)); varianzaxHipl_vert(2,10)./(varianzayHipl_vert(2,10)+varianzazHipl_vert(2,10)+varianzaxHipl_vert(2,10)); varianzaxHipl_vert(3,6)./(varianzayHipl_vert(3,6)+varianzazHipl_vert(3,6)+varianzaxHipl_vert(3,6))]])
title('HipL variance ratio ReachV')
subplot(2,2,4)
bar([varianzaxHipr_vert(:,1)./(varianzayHipr_vert(:,1)+varianzazHipr_vert(:,1)+varianzaxHipr_vert(:,1)) [varianzaxHipr_vert(1,7)./(varianzayHipr_vert(1,7)+varianzazHipr_vert(1,7)+varianzaxHipr_vert(1,7)); varianzaxHipr_vert(2,10)./(varianzayHipr_vert(2,10)+varianzazHipr_vert(2,10)+varianzaxHipr_vert(2,10)); varianzaxHipr_vert(3,6)./(varianzayHipr_vert(3,6)+varianzazHipr_vert(3,6)+varianzaxHipr_vert(3,6))]])
title('HipR variance ratio ReachV')

%std reach orizzontale
figure
subplot(2,3,1)
bar([stdxHipl_hor(:,1) [stdxHipl_hor(1,7); stdxHipl_hor(2,10); stdxHipl_hor(3,6)]])
title('Hip left std_x Hor')
subplot(2,3,2)
bar([stdyHipl_hor(:,1) [stdyHipl_hor(1,7); stdyHipl_hor(2,10); stdyHipl_hor(3,6)]])
title('Hip left std_y Hor')
subplot(2,3,3)
bar([stdzHipl_hor(:,1) [stdzHipl_hor(1,7); stdzHipl_hor(2,10); stdzHipl_hor(3,6)]])
title('Hip left std_z Hor')
subplot(2,3,4)
bar([stdxHipr_hor(:,1) [stdxHipr_hor(1,7); stdxHipr_hor(2,10); stdxHipr_hor(3,6)]])
title('Hip right std_x Hor')
subplot(2,3,5)
bar([stdyHipr_hor(:,1) [stdyHipr_hor(1,7); stdyHipr_hor(2,10); stdyHipr_hor(3,6)]])
title('Hip right std_y Hor')
subplot(2,3,6)
bar([stdzHipr_hor(:,1) [stdzHipr_hor(1,7); stdzHipr_hor(2,10); stdzHipr_hor(3,6)]])
title('Hip right std_z Hor')
% std reach verticale
figure
subplot(2,3,1)
bar([stdxHipl_vert(:,1) [stdxHipl_vert(1,7); stdxHipl_vert(2,10); stdxHipl_vert(3,6)]])
title('Hip left std_x vert')
subplot(2,3,2)
bar([stdyHipl_vert(:,1) [stdyHipl_vert(1,7); stdyHipl_vert(2,10); stdyHipl_vert(3,6)]])
title('Hip left std_y vert')
subplot(2,3,3)
bar([stdzHipl_vert(:,1) [stdzHipl_vert(1,7); stdzHipl_vert(2,10); stdzHipl_vert(3,6)]])
title('Hip left std_z vert')
subplot(2,3,4)
bar([stdxHipr_vert(:,1) [stdxHipr_vert(1,7); stdxHipr_vert(2,10); stdxHipr_vert(3,6)]])
title('Hip right std_x vert')
subplot(2,3,5)
bar([stdyHipr_vert(:,1) [stdyHipr_vert(1,7); stdyHipr_vert(2,10); stdyHipr_vert(3,6)]])
title('Hip right std_y vert')
subplot(2,3,6)
bar([stdzHipr_vert(:,1) [stdzHipr_vert(1,7); stdzHipr_vert(2,10); stdzHipr_vert(3,6)]])
title('Hip right std_z vert')
% rapporto tra varianze
figure
subplot(2,2,1)
bar([stdzHipl_hor(:,1)./(stdxHipl_hor(:,1)+stdyHipl_hor(:,1)) [stdzHipl_hor(1,7)./(stdxHipl_hor(1,7)+stdyHipl_hor(1,7)); stdzHipl_hor(2,10)./(stdxHipl_hor(2,10)+stdyHipl_hor(2,10)); stdzHipl_hor(3,6)./(stdxHipl_hor(3,6)+stdyHipl_hor(3,6))]])
title('HipL std ratio ReachH')
subplot(2,2,2)
bar([stdzHipr_hor(:,1)./(stdxHipr_hor(:,1)+stdyHipr_hor(:,1)) [stdzHipr_hor(1,7)./(stdxHipr_hor(1,7)+stdyHipr_hor(1,7)); stdzHipr_hor(2,10)./(stdxHipr_hor(2,10)+stdyHipr_hor(2,10)); stdzHipr_hor(3,6)./(stdxHipr_hor(3,6)+stdyHipr_hor(3,6))]])
title('HipR std ratio ReachH')
subplot(2,2,3)
bar([stdxHipl_vert(:,1)./(stdyHipl_vert(:,1)+stdzHipl_vert(:,1)) [stdxHipl_vert(1,7)./(stdyHipl_vert(1,7)+stdzHipl_vert(1,7)); stdxHipl_vert(2,10)./(stdyHipl_vert(2,10)+stdzHipl_vert(2,10)); stdxHipl_vert(3,6)./(stdyHipl_vert(3,6)+stdzHipl_vert(3,6))]])
title('HipL std ratio ReachV')
subplot(2,2,4)
bar([stdxHipr_vert(:,1)./(stdyHipr_vert(:,1)+stdzHipr_vert(:,1)) [stdxHipr_vert(1,7)./(stdyHipr_vert(1,7)+stdzHipr_vert(1,7)); stdxHipr_vert(2,10)./(stdyHipr_vert(2,10)+stdzHipr_vert(2,10)); stdxHipr_vert(3,6)./(stdyHipr_vert(3,6)+stdzHipr_vert(3,6))]])
title('HipR std ratio ReachV')

figure
subplot(2,2,1)
bar([stdzHipl_hor(:,1)./(stdxHipl_hor(:,1)+stdyHipl_hor(:,1)+stdzHipl_hor(:,1)) [stdzHipl_hor(1,7)./(stdxHipl_hor(1,7)+stdyHipl_hor(1,7)+stdzHipl_hor(1,7)); stdzHipl_hor(2,10)./(stdxHipl_hor(2,10)+stdyHipl_hor(2,10)+stdzHipl_hor(2,10)); stdzHipl_hor(3,6)./(stdxHipl_hor(3,6)+stdyHipl_hor(3,6)+stdzHipl_hor(3,6))]])
title('HipL std ratio ReachH')
subplot(2,2,2)
bar([stdzHipr_hor(:,1)./(stdxHipr_hor(:,1)+stdyHipr_hor(:,1)+stdzHipr_hor(:,1)) [stdzHipr_hor(1,7)./(stdxHipr_hor(1,7)+stdyHipr_hor(1,7)+stdzHipr_hor(1,7)); stdzHipr_hor(2,10)./(stdxHipr_hor(2,10)+stdyHipr_hor(2,10)+stdzHipr_hor(2,10)); stdzHipr_hor(3,6)./(stdxHipr_hor(3,6)+stdyHipr_hor(3,6)+stdzHipr_hor(3,6))]])
title('HipR std ratio ReachH')
subplot(2,2,3)
bar([stdxHipl_vert(:,1)./(stdyHipl_vert(:,1)+stdzHipl_vert(:,1)+stdxHipl_vert(:,1)) [stdxHipl_vert(1,7)./(stdyHipl_vert(1,7)+stdzHipl_vert(1,7)+stdxHipl_vert(1,7)); stdxHipl_vert(2,10)./(stdyHipl_vert(2,10)+stdzHipl_vert(2,10)+stdxHipl_vert(2,10)); stdxHipl_vert(3,6)./(stdyHipl_vert(3,6)+stdzHipl_vert(3,6)+stdxHipl_vert(3,6))]])
title('HipL std ratio ReachV')
subplot(2,2,4)
bar([stdxHipr_vert(:,1)./(stdyHipr_vert(:,1)+stdzHipr_vert(:,1)+stdxHipr_vert(:,1)) [stdxHipr_vert(1,7)./(stdyHipr_vert(1,7)+stdzHipr_vert(1,7)+stdxHipr_vert(1,7)); stdxHipr_vert(2,10)./(stdyHipr_vert(2,10)+stdzHipr_vert(2,10)+stdxHipr_vert(2,10)); stdxHipr_vert(3,6)./(stdyHipr_vert(3,6)+stdzHipr_vert(3,6)+stdxHipr_vert(3,6))]])
title('HipR std ratio ReachV')

%stesse figure ma con valori mediati
%var mean reach H hip
figure
subplot(2,3,1)
bar([squeeze(varmean_hipL_H(1,1,:)) [varmean_hipL_H(1,7,1);varmean_hipL_H(1,10,2);varmean_hipL_H(1,6,3)]])
title('mean varX Hip_L Reach H')
subplot(2,3,2)
bar([squeeze(varmean_hipL_H(2,1,:)) [varmean_hipL_H(2,7,1);varmean_hipL_H(2,10,2);varmean_hipL_H(2,6,3)]])
title('mean varY Hip_L Reach H')
subplot(2,3,3)
bar([squeeze(varmean_hipL_H(3,1,:)) [varmean_hipL_H(3,7,1);varmean_hipL_H(3,10,2);varmean_hipL_H(3,6,3)]])
title('mean varZ Hip_L Reach H')
subplot(2,3,4)
bar([squeeze(varmean_hipR_H(1,1,:)) [varmean_hipR_H(1,7,1);varmean_hipR_H(1,10,2);varmean_hipR_H(1,6,3)]])
title('mean varX Hip_R Reach H')
subplot(2,3,5)
bar([squeeze(varmean_hipR_H(2,1,:)) [varmean_hipR_H(2,7,1);varmean_hipR_H(2,10,2);varmean_hipR_H(2,6,3)]])
title('mean varY Hip_R Reach H')
subplot(2,3,6)
bar([squeeze(varmean_hipR_H(3,1,:)) [varmean_hipR_H(3,7,1);varmean_hipR_H(3,10,2);varmean_hipR_H(3,6,3)]])
title('mean varZ Hip_R Reach H')
%var mean reach H shoulder
figure
subplot(2,3,1)
bar([squeeze(varmean_shL_H(1,1,:)) [varmean_shL_H(1,7,1);varmean_shL_H(1,10,2);varmean_shL_H(1,6,3)]])
title('mean varX Sh_L Reach H')
subplot(2,3,2)
bar([squeeze(varmean_shL_H(2,1,:)) [varmean_shL_H(2,7,1);varmean_shL_H(2,10,2);varmean_shL_H(2,6,3)]])
title('mean varY Sh_L Reach H')
subplot(2,3,3)
bar([squeeze(varmean_shL_H(3,1,:)) [varmean_shL_H(3,7,1);varmean_shL_H(3,10,2);varmean_shL_H(3,6,3)]])
title('mean varZ Sh_L Reach H')
subplot(2,3,4)
bar([squeeze(varmean_shR_H(1,1,:)) [varmean_shR_H(1,7,1);varmean_shR_H(1,10,2);varmean_shR_H(1,6,3)]])
title('mean varX Sh_R Reach H')
subplot(2,3,5)
bar([squeeze(varmean_shR_H(2,1,:)) [varmean_shR_H(2,7,1);varmean_shR_H(2,10,2);varmean_shR_H(2,6,3)]])
title('mean varY Sh_R Reach H')
subplot(2,3,6)
bar([squeeze(varmean_shR_H(3,1,:)) [varmean_shR_H(3,7,1);varmean_shR_H(3,10,2);varmean_shR_H(3,6,3)]])
title('mean varZ Sh_R Reach H')

%var mean reach V hips
figure
subplot(2,3,1)
bar([squeeze(varmean_hipL_V(1,1,:)) [varmean_hipL_V(1,7,1);varmean_hipL_V(1,10,2);varmean_hipL_V(1,6,3)]])
title('mean varX Hip_L Reach V')
subplot(2,3,2)
bar([squeeze(varmean_hipL_V(2,1,:)) [varmean_hipL_V(2,7,1);varmean_hipL_V(2,10,2);varmean_hipL_V(2,6,3)]])
title('mean varY Hip_L Reach V')
subplot(2,3,3)
bar([squeeze(varmean_hipL_V(3,1,:)) [varmean_hipL_V(3,7,1);varmean_hipL_V(3,10,2);varmean_hipL_V(3,6,3)]])
title('mean varZ Hip_L Reach V')
subplot(2,3,4)
bar([squeeze(varmean_hipR_V(1,1,:)) [varmean_hipR_V(1,7,1);varmean_hipR_V(1,10,2);varmean_hipR_V(1,6,3)]])
title('mean varX Hip_R Reach V')
subplot(2,3,5)
bar([squeeze(varmean_hipR_V(2,1,:)) [varmean_hipR_V(2,7,1);varmean_hipR_V(2,10,2);varmean_hipR_V(2,6,3)]])
title('mean varY Hip_R Reach V')
subplot(2,3,6)
bar([squeeze(varmean_hipR_V(3,1,:)) [varmean_hipR_V(3,7,1);varmean_hipR_V(3,10,2);varmean_hipR_V(3,6,3)]])
title('mean varZ Hip_R Reach V')
%var mean reach V shoulder
figure
subplot(2,3,1)
bar([squeeze(varmean_shL_V(1,1,:)) [varmean_shL_V(1,7,1);varmean_shL_V(1,10,2);varmean_shL_V(1,6,3)]])
title('mean varX Sh_L Reach V')
subplot(2,3,2)
bar([squeeze(varmean_shL_V(2,1,:)) [varmean_shL_V(2,7,1);varmean_shL_V(2,10,2);varmean_shL_V(2,6,3)]])
title('mean varY Sh_L Reach V')
subplot(2,3,3)
bar([squeeze(varmean_shL_V(3,1,:)) [varmean_shL_V(3,7,1);varmean_shL_V(3,10,2);varmean_shL_V(3,6,3)]])
title('mean varZ Sh_L Reach V')
subplot(2,3,4)
bar([squeeze(varmean_shR_V(1,1,:)) [varmean_shR_V(1,7,1);varmean_shR_V(1,10,2);varmean_shR_V(1,6,3)]])
title('mean varX Sh_R Reach V')
subplot(2,3,5)
bar([squeeze(varmean_shR_V(2,1,:)) [varmean_shR_V(2,7,1);varmean_shR_V(2,10,2);varmean_shR_V(2,6,3)]])
title('mean varY Sh_R Reach V')
subplot(2,3,6)
bar([squeeze(varmean_shR_V(3,1,:)) [varmean_shR_V(3,7,1);varmean_shR_V(3,10,2);varmean_shR_V(3,6,3)]])
title('mean varZ Sh_R Reach V')

%std mean Reach H
figure
subplot(2,3,1)
bar([squeeze(stdmean_hipL_H(1,1,:)) [stdmean_hipL_H(1,7,1);stdmean_hipL_H(1,10,2);stdmean_hipL_H(1,6,3)]])
title('mean stdX Hip_L Reach H')
subplot(2,3,2)
bar([squeeze(stdmean_hipL_H(2,1,:)) [stdmean_hipL_H(2,7,1);stdmean_hipL_H(2,10,2);stdmean_hipL_H(2,6,3)]])
title('mean stdY Hip_L Reach H')
subplot(2,3,3)
bar([squeeze(stdmean_hipL_H(3,1,:)) [stdmean_hipL_H(3,7,1);stdmean_hipL_H(3,10,2);stdmean_hipL_H(3,6,3)]])
title('mean stdZ Hip_L Reach H')
subplot(2,3,4)
bar([squeeze(stdmean_hipR_H(1,1,:)) [stdmean_hipR_H(1,7,1);stdmean_hipR_H(1,10,2);stdmean_hipR_H(1,6,3)]])
title('mean stdX Hip_R Reach H')
subplot(2,3,5)
bar([squeeze(stdmean_hipR_H(2,1,:)) [stdmean_hipR_H(2,7,1);stdmean_hipR_H(2,10,2);stdmean_hipR_H(2,6,3)]])
title('mean stdY Hip_R Reach H')
subplot(2,3,6)
bar([squeeze(stdmean_hipR_H(3,1,:)) [stdmean_hipR_H(3,7,1);stdmean_hipR_H(3,10,2);stdmean_hipR_H(3,6,3)]])
title('mean stdZ Hip_R Reach H')
%std mean Reach H shoulder
figure
subplot(2,3,1)
bar([squeeze(stdmean_shL_H(1,1,:)) [stdmean_shL_H(1,7,1);stdmean_shL_H(1,10,2);stdmean_shL_H(1,6,3)]])
title('mean stdX Sh_L Reach H')
subplot(2,3,2)
bar([squeeze(stdmean_shL_H(2,1,:)) [stdmean_shL_H(2,7,1);stdmean_shL_H(2,10,2);stdmean_shL_H(2,6,3)]])
title('mean stdY Sh_L Reach H')
subplot(2,3,3)
bar([squeeze(stdmean_shL_H(3,1,:)) [stdmean_shL_H(3,7,1);stdmean_shL_H(3,10,2);stdmean_shL_H(3,6,3)]])
title('mean stdZ Sh_L Reach H')
subplot(2,3,4)
bar([squeeze(stdmean_shR_H(1,1,:)) [stdmean_shR_H(1,7,1);stdmean_shR_H(1,10,2);stdmean_shR_H(1,6,3)]])
title('mean stdX Sh_R Reach H')
subplot(2,3,5)
bar([squeeze(stdmean_shR_H(2,1,:)) [stdmean_shR_H(2,7,1);stdmean_shR_H(2,10,2);stdmean_shR_H(2,6,3)]])
title('mean stdY Sh_R Reach H')
subplot(2,3,6)
bar([squeeze(stdmean_shR_H(3,1,:)) [stdmean_shR_H(3,7,1);stdmean_shR_H(3,10,2);stdmean_shR_H(3,6,3)]])
title('mean stdZ Sh_R Reach H')

%std mean Reach V
figure
subplot(2,3,1)
bar([squeeze(stdmean_hipL_V(1,1,:)) [stdmean_hipL_V(1,7,1);stdmean_hipL_V(1,10,2);stdmean_hipL_V(1,6,3)]])
title('mean stdX Hip_L Reach V')
subplot(2,3,2)
bar([squeeze(stdmean_hipL_V(2,1,:)) [stdmean_hipL_V(2,7,1);stdmean_hipL_V(2,10,2);stdmean_hipL_V(2,6,3)]])
title('mean stdY Hip_L Reach V')
subplot(2,3,3)
bar([squeeze(stdmean_hipL_V(3,1,:)) [stdmean_hipL_V(3,7,1);stdmean_hipL_V(3,10,2);stdmean_hipL_V(3,6,3)]])
title('mean stdZ Hip_L Reach V')
subplot(2,3,4)
bar([squeeze(stdmean_hipR_V(1,1,:)) [stdmean_hipR_V(1,7,1);stdmean_hipR_V(1,10,2);stdmean_hipR_V(1,6,3)]])
title('mean stdX Hip_R Reach V')
subplot(2,3,5)
bar([squeeze(stdmean_hipR_V(2,1,:)) [stdmean_hipR_V(2,7,1);stdmean_hipR_V(2,10,2);stdmean_hipR_V(2,6,3)]])
title('mean stdY Hip_R Reach V')
subplot(2,3,6)
bar([squeeze(stdmean_hipR_V(3,1,:)) [stdmean_hipR_V(3,7,1);stdmean_hipR_V(3,10,2);stdmean_hipR_V(3,6,3)]])
title('mean stdZ Hip_R Reach V')
%std mean Reach V shoulder
figure
subplot(2,3,1)
bar([squeeze(stdmean_shL_V(1,1,:)) [stdmean_shL_V(1,7,1);stdmean_shL_V(1,10,2);stdmean_shL_V(1,6,3)]])
title('mean stdX Sh_L Reach V')
subplot(2,3,2)
bar([squeeze(stdmean_shL_V(2,1,:)) [stdmean_shL_V(2,7,1);stdmean_shL_V(2,10,2);stdmean_shL_V(2,6,3)]])
title('mean stdY Sh_L Reach V')
subplot(2,3,3)
bar([squeeze(stdmean_shL_V(3,1,:)) [stdmean_shL_V(3,7,1);stdmean_shL_V(3,10,2);stdmean_shL_V(3,6,3)]])
title('mean stdZ Sh_L Reach V')
subplot(2,3,4)
bar([squeeze(stdmean_shR_V(1,1,:)) [stdmean_shR_V(1,7,1);stdmean_shR_V(1,10,2);stdmean_shR_V(1,6,3)]])
title('mean stdX Sh_R Reach V')
subplot(2,3,5)
bar([squeeze(stdmean_shR_V(2,1,:)) [stdmean_shR_V(2,7,1);stdmean_shR_V(2,10,2);stdmean_shR_V(2,6,3)]])
title('mean stdY Sh_R Reach V')
subplot(2,3,6)
bar([squeeze(stdmean_shR_V(3,1,:)) [stdmean_shR_V(3,7,1);stdmean_shR_V(3,10,2);stdmean_shR_V(3,6,3)]])
title('mean stdZ Sh_R Reach V')

%std ratio reach H hips
figure
subplot(2,2,1)
bar([squeeze(stdmean_hipL_H(3,1,:))./(squeeze(stdmean_hipL_H(1,1,:))+squeeze(stdmean_hipL_H(2,1,:))) [stdmean_hipL_H(3,7,1)/(stdmean_hipL_H(1,7,1)+stdmean_hipL_H(2,7,1));stdmean_hipL_H(3,10,2)/(stdmean_hipL_H(1,10,2)+stdmean_hipL_H(2,10,2));stdmean_hipL_H(3,6,3)/(stdmean_hipL_H(1,6,3)+stdmean_hipL_H(2,6,3))]])
title('std ratio reach H hip_L')
subplot(2,2,2)
bar([squeeze(stdmean_hipR_H(3,1,:))./(squeeze(stdmean_hipR_H(1,1,:))+squeeze(stdmean_hipR_H(2,1,:))) [stdmean_hipR_H(3,7,1)/(stdmean_hipR_H(1,7,1)+stdmean_hipR_H(2,7,1));stdmean_hipR_H(3,10,2)/(stdmean_hipR_H(1,10,2)+stdmean_hipR_H(2,10,2));stdmean_hipR_H(3,6,3)/(stdmean_hipR_H(1,6,3)+stdmean_hipR_H(2,6,3))]])
title('std ration reach H hip_R')

subplot(2,2,3)
bar([squeeze(stdmean_hipL_V(1,1,:))./(squeeze(stdmean_hipL_V(2,1,:))+squeeze(stdmean_hipL_V(3,1,:))) [stdmean_hipL_V(1,7,1)/(stdmean_hipL_V(2,7,1)+stdmean_hipL_V(3,7,1));stdmean_hipL_V(1,10,2)/(stdmean_hipL_V(2,10,2)+stdmean_hipL_V(3,10,2));stdmean_hipL_V(1,6,3)/(stdmean_hipL_V(2,6,3)+stdmean_hipL_V(3,6,3))]])
title('std ratio reach V hip_L')
subplot(2,2,4)
bar([squeeze(stdmean_hipR_V(1,1,:))./(squeeze(stdmean_hipR_V(2,1,:))+squeeze(stdmean_hipR_V(3,1,:))) [stdmean_hipR_V(1,7,1)/(stdmean_hipR_V(2,7,1)+stdmean_hipR_V(3,7,1));stdmean_hipR_V(1,10,2)/(stdmean_hipR_V(2,10,2)+stdmean_hipR_V(3,10,2));stdmean_hipR_V(1,6,3)/(stdmean_hipR_V(2,6,3)+stdmean_hipR_V(3,6,3))]])
title('std ratio reach V hip_R')
%shoulders
figure
subplot(2,2,1)
bar([squeeze(stdmean_shL_H(3,1,:))./(squeeze(stdmean_shL_H(1,1,:))+squeeze(stdmean_shL_H(2,1,:))) [stdmean_shL_H(3,7,1)/(stdmean_shL_H(1,7,1)+stdmean_shL_H(2,7,1));stdmean_shL_H(3,10,2)/(stdmean_shL_H(1,10,2)+stdmean_shL_H(2,10,2));stdmean_shL_H(3,6,3)/(stdmean_shL_H(1,6,3)+stdmean_shL_H(2,6,3))]])
title('std ratio reach H sh_L')
subplot(2,2,2)
bar([squeeze(stdmean_shR_H(3,1,:))./(squeeze(stdmean_shR_H(1,1,:))+squeeze(stdmean_shR_H(2,1,:))) [stdmean_shR_H(3,7,1)/(stdmean_shR_H(1,7,1)+stdmean_shR_H(2,7,1));stdmean_shR_H(3,10,2)/(stdmean_shR_H(1,10,2)+stdmean_shR_H(2,10,2));stdmean_shR_H(3,6,3)/(stdmean_shR_H(1,6,3)+stdmean_shR_H(2,6,3))]])
title('std ration reach H sh_R')

subplot(2,2,3)
bar([squeeze(stdmean_shL_V(1,1,:))./(squeeze(stdmean_shL_V(2,1,:))+squeeze(stdmean_shL_V(3,1,:))) [stdmean_shL_V(1,7,1)/(stdmean_shL_V(2,7,1)+stdmean_shL_V(3,7,1));stdmean_shL_V(1,10,2)/(stdmean_shL_V(2,10,2)+stdmean_shL_V(3,10,2));stdmean_shL_V(1,6,3)/(stdmean_shL_V(2,6,3)+stdmean_shL_V(3,6,3))]])
title('std ratio reach V sh_L')
subplot(2,2,4)
bar([squeeze(stdmean_shR_V(1,1,:))./(squeeze(stdmean_shR_V(2,1,:))+squeeze(stdmean_shR_V(3,1,:))) [stdmean_shR_V(1,7,1)/(stdmean_shR_V(2,7,1)+stdmean_shR_V(3,7,1));stdmean_shR_V(1,10,2)/(stdmean_shR_V(2,10,2)+stdmean_shR_V(3,10,2));stdmean_shR_V(1,6,3)/(stdmean_shR_V(2,6,3)+stdmean_shR_V(3,6,3))]])
title('std ratio reach V sh_R')

%variance ratio reach H
figure
subplot(2,2,1)
bar([squeeze(varmean_hipL_H(3,1,:))./(squeeze(varmean_hipL_H(1,1,:))+squeeze(varmean_hipL_H(2,1,:))) [varmean_hipL_H(3,7,1)/(varmean_hipL_H(1,7,1)+varmean_hipL_H(2,7,1));varmean_hipL_H(3,10,2)/(varmean_hipL_H(1,10,2)+varmean_hipL_H(2,10,2));varmean_hipL_H(3,6,3)/(varmean_hipL_H(1,6,3)+varmean_hipL_H(2,6,3))]])
title('var ratio reach H hip_L')
subplot(2,2,2)
bar([squeeze(varmean_hipR_H(3,1,:))./(squeeze(varmean_hipR_H(1,1,:))+squeeze(varmean_hipR_H(2,1,:))) [varmean_hipR_H(3,7,1)/(varmean_hipR_H(1,7,1)+varmean_hipR_H(2,7,1));varmean_hipR_H(3,10,2)/(varmean_hipR_H(1,10,2)+varmean_hipR_H(2,10,2));varmean_hipR_H(3,6,3)/(varmean_hipR_H(1,6,3)+varmean_hipR_H(2,6,3))]])
title('var ration reach H hip_R')

subplot(2,2,3)
bar([squeeze(varmean_hipL_V(1,1,:))./(squeeze(varmean_hipL_V(2,1,:))+squeeze(varmean_hipL_V(3,1,:))) [varmean_hipL_V(1,7,1)/(varmean_hipL_V(2,7,1)+varmean_hipL_V(3,7,1));varmean_hipL_V(1,10,2)/(varmean_hipL_V(2,10,2)+varmean_hipL_V(3,10,2));varmean_hipL_V(1,6,3)/(varmean_hipL_V(2,6,3)+varmean_hipL_V(3,6,3))]])
title('var ratio reach V hip_L')
subplot(2,2,4)
bar([squeeze(varmean_hipR_V(1,1,:))./(squeeze(varmean_hipR_V(2,1,:))+squeeze(varmean_hipR_V(3,1,:))) [varmean_hipR_V(1,7,1)/(varmean_hipR_V(2,7,1)+varmean_hipR_V(3,7,1));varmean_hipR_V(1,10,2)/(varmean_hipR_V(2,10,2)+varmean_hipR_V(3,10,2));varmean_hipR_V(1,6,3)/(varmean_hipR_V(2,6,3)+varmean_hipR_V(3,6,3))]])
title('var ratio reach H hip_R')
%variance ratio reach H shoulder


% delta hips mean Reach H
figure
subplot(2,3,1)
bar([squeeze(deltamean_hipL_trgt1H(1,1,:)) [deltamean_hipL_trgt1H(1,7,1);deltamean_hipL_trgt1H(1,10,2);deltamean_hipL_trgt1H(1,6,3)]])
title('mean deltaX Hip_L Reach H trgt1')
subplot(2,3,2)
bar([squeeze(deltamean_hipL_trgt1H(2,1,:)) [deltamean_hipL_trgt1H(2,7,1);deltamean_hipL_trgt1H(2,10,2);deltamean_hipL_trgt1H(2,6,3)]])
title('mean deltaY Hip_L Reach H trgt1')
subplot(2,3,3)
bar([squeeze(deltamean_hipL_trgt1H(3,1,:)) [deltamean_hipL_trgt1H(3,7,1);deltamean_hipL_trgt1H(3,10,2);deltamean_hipL_trgt1H(3,6,3)]])
title('mean deltaZ Hip_L Reach H trgt1')
subplot(2,3,4)
bar([squeeze(deltamean_hipR_trgt1H(1,1,:)) [deltamean_hipR_trgt1H(1,7,1);deltamean_hipR_trgt1H(1,10,2);deltamean_hipR_trgt1H(1,6,3)]])
title('mean deltaX Hip_R Reach H trgt1')
subplot(2,3,5)
bar([squeeze(deltamean_hipR_trgt1H(2,1,:)) [deltamean_hipR_trgt1H(2,7,1);deltamean_hipR_trgt1H(2,10,2);deltamean_hipR_trgt1H(2,6,3)]])
title('mean deltaY Hip_R Reach H trgt1')
subplot(2,3,6)
bar([squeeze(deltamean_hipR_trgt1H(3,1,:)) [deltamean_hipR_trgt1H(3,7,1);deltamean_hipR_trgt1H(3,10,2);deltamean_hipR_trgt1H(3,6,3)]])
title('mean deltaZ Hip_R Reach H trgt1')

figure
subplot(2,3,1)
bar([squeeze(deltamean_hipL_trgt2H(1,1,:)) [deltamean_hipL_trgt2H(1,7,1);deltamean_hipL_trgt2H(1,10,2);deltamean_hipL_trgt2H(1,6,3)]])
title('mean deltaX Hip_L Reach H trgt2')
subplot(2,3,2)
bar([squeeze(deltamean_hipL_trgt2H(2,1,:)) [deltamean_hipL_trgt2H(2,7,1);deltamean_hipL_trgt2H(2,10,2);deltamean_hipL_trgt2H(2,6,3)]])
title('mean deltaY Hip_L Reach H trgt2')
subplot(2,3,3)
bar([squeeze(deltamean_hipL_trgt2H(3,1,:)) [deltamean_hipL_trgt2H(3,7,1);deltamean_hipL_trgt2H(3,10,2);deltamean_hipL_trgt2H(3,6,3)]])
title('mean deltaZ Hip_L Reach H trgt2')
subplot(2,3,4)
bar([squeeze(deltamean_hipR_trgt2H(1,1,:)) [deltamean_hipR_trgt2H(1,7,1);deltamean_hipR_trgt2H(1,10,2);deltamean_hipR_trgt2H(1,6,3)]])
title('mean deltaX Hip_R Reach H trgt2')
subplot(2,3,5)
bar([squeeze(deltamean_hipR_trgt2H(2,1,:)) [deltamean_hipR_trgt2H(2,7,1);deltamean_hipR_trgt2H(2,10,2);deltamean_hipR_trgt2H(2,6,3)]])
title('mean deltaY Hip_R Reach H trgt2')
subplot(2,3,6)
bar([squeeze(deltamean_hipR_trgt2H(3,1,:)) [deltamean_hipR_trgt2H(3,7,1);deltamean_hipR_trgt2H(3,10,2);deltamean_hipR_trgt2H(3,6,3)]])
title('mean deltaZ Hip_R Reach H trgt2')
% delta hips mean Reach V
figure
subplot(2,3,1)
bar([squeeze(deltamean_hipL_trgt1V(1,1,:)) [deltamean_hipL_trgt1V(1,7,1);deltamean_hipL_trgt1V(1,10,2);deltamean_hipL_trgt1V(1,6,3)]])
title('mean deltaX Hip_L Reach V trgt1')
subplot(2,3,2)
bar([squeeze(deltamean_hipL_trgt1V(2,1,:)) [deltamean_hipL_trgt1V(2,7,1);deltamean_hipL_trgt1V(2,10,2);deltamean_hipL_trgt1V(2,6,3)]])
title('mean deltaY Hip_L Reach V trgt1')
subplot(2,3,3)
bar([squeeze(deltamean_hipL_trgt1V(3,1,:)) [deltamean_hipL_trgt1V(3,7,1);deltamean_hipL_trgt1V(3,10,2);deltamean_hipL_trgt1V(3,6,3)]])
title('mean deltaZ Hip_L Reach V trgt1')
subplot(2,3,4)
bar([squeeze(deltamean_hipR_trgt1V(1,1,:)) [deltamean_hipR_trgt1V(1,7,1);deltamean_hipR_trgt1V(1,10,2);deltamean_hipR_trgt1V(1,6,3)]])
title('mean deltaX Hip_R Reach V trgt1')
subplot(2,3,5)
bar([squeeze(deltamean_hipR_trgt1V(2,1,:)) [deltamean_hipR_trgt1V(2,7,1);deltamean_hipR_trgt1V(2,10,2);deltamean_hipR_trgt1V(2,6,3)]])
title('mean deltaY Hip_R Reach V trgt1')
subplot(2,3,6)
bar([squeeze(deltamean_hipR_trgt1V(3,1,:)) [deltamean_hipR_trgt1V(3,7,1);deltamean_hipR_trgt1V(3,10,2);deltamean_hipR_trgt1V(3,6,3)]])
title('mean deltaZ Hip_R Reach V trgt1')

figure
subplot(2,3,1)
bar([squeeze(deltamean_hipL_trgt2V(1,1,:)) [deltamean_hipL_trgt2V(1,7,1);deltamean_hipL_trgt2V(1,10,2);deltamean_hipL_trgt2V(1,6,3)]])
title('mean deltaX Hip_L Reach V trgt2')
subplot(2,3,2)
bar([squeeze(deltamean_hipL_trgt2V(2,1,:)) [deltamean_hipL_trgt2V(2,7,1);deltamean_hipL_trgt2V(2,10,2);deltamean_hipL_trgt2V(2,6,3)]])
title('mean deltaY Hip_L Reach V trgt2')
subplot(2,3,3)
bar([squeeze(deltamean_hipL_trgt2V(3,1,:)) [deltamean_hipL_trgt2V(3,7,1);deltamean_hipL_trgt2V(3,10,2);deltamean_hipL_trgt2V(3,6,3)]])
title('mean deltaZ Hip_L Reach V trgt2')
subplot(2,3,4)
bar([squeeze(deltamean_hipR_trgt2V(1,1,:)) [deltamean_hipR_trgt2V(1,7,1);deltamean_hipR_trgt2V(1,10,2);deltamean_hipR_trgt2V(1,6,3)]])
title('mean deltaX Hip_R Reach V trgt2')
subplot(2,3,5)
bar([squeeze(deltamean_hipR_trgt2V(2,1,:)) [deltamean_hipR_trgt2V(2,7,1);deltamean_hipR_trgt2V(2,10,2);deltamean_hipR_trgt2V(2,6,3)]])
title('mean deltaY Hip_R Reach V trgt2')
subplot(2,3,6)
bar([squeeze(deltamean_hipR_trgt2V(3,1,:)) [deltamean_hipR_trgt2V(3,7,1);deltamean_hipR_trgt2V(3,10,2);deltamean_hipR_trgt2V(3,6,3)]])
title('mean deltaZ Hip_R Reach V trgt2')
